### ISSUE TITLE
NanoLyse install isue:q

### ISSUE THREAD

**Issue by tderrien** [wdecoster/nanopack#9]
Hi,

It seems that installing Nanopack failed at the NanoLyse package.

```
$ pip install nanopack
Defaulting to user installation because normal site-packages is not writeable
Collecting nanopack
  Using cached nanopack-1.0.3.tar.gz (2.7 kB)
Collecting NanoPlot>=1.29.0
  Using cached NanoPlot-1.30.0.tar.gz (36 kB)
Collecting NanoStat>=1.2.0
  Using cached NanoStat-1.2.0.tar.gz (5.6 kB)
Collecting NanoFilt>=2.6.0
  Using cached NanoFilt-2.7.0.tar.gz (7.3 kB)
Collecting NanoLyse>=1.1.0
  Using cached NanoLyse-1.1.1.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /local/miniconda3/envs/python-3.7.6/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oo9cvsxa/NanoLyse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oo9cvsxa/NanoLyse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-oo9cvsxa/NanoLyse/pip-egg-info
         cwd: /tmp/pip-install-oo9cvsxa/NanoLyse/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oo9cvsxa/NanoLyse/setup.py", line 15, in <module>
        long_description=open(path.join(here, "README.md")).read(),
      File "/local/miniconda3/envs/python-3.7.6/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-oo9cvsxa/NanoLyse/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Since I was more interested in Nanocomp, I tried :
`pip install nanoComp`

And it worked like a charm.

All the best,

Thomas

**Comment by wdecoster** [comment]
Thanks for reporting this! I've identified the issue and fixed it in NanoLyse v1.1.2.
